const MOBIL_DATA = [
  {
    "name":"Rocky",
    "brand":"Astra",
    "price":2.99,
    "image":"rocky.png"
  },
  {
    "name":"Alya",
    "brand":"Astra",
    "price":4.99,
    "image":"alya.png"
  },
  {
    "name":"Sigra",
    "brand":"Astra",
    "price":1.49,
    "image":"sigra.png"
  },
  {
    "name":"Xenia",
    "brand":"Astra",
    "price":2.99,
    "image":"xenia.png"
  },
];